This data comes from this site: https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/docApi

In [4]:
import pandas as pd

import json

with open('../DATA/RAW_CRIME_DATA/response_1771261925308.json') as f:
    data = json.load(f)

all_agencies = []

for county, agencies in data.items():
    for agency in agencies:
        agency['county_name'] = county
        all_agencies.append(agency)

df_CO = pd.DataFrame(all_agencies)

df_CO

,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,agency_type_name,nibrs_start_date,county_name
0,CO0050700,BACA,True,37.306678,-102.537765,CO,Colorado,Walsh Police Department,City,2004-10-01,BACA
1,CO0050000,BACA,True,37.412470,-102.614260,CO,Colorado,Baca County Sheriff's Office,County,1997-01-01,BACA
2,CO0050100,BACA,True,37.406647,-102.616520,CO,Colorado,Springfield Police Department,City,2003-01-01,BACA
3,CO0060000,BENT,True,37.931891,-103.077584,CO,Colorado,Bent County Sheriff's Office,County,1997-01-01,BENT
4,CO0330000,LAKE,True,39.205341,-106.350079,CO,Colorado,Lake County Sheriff's Office,County,1997-01-01,LAKE
...,...,...,...,...,...,...,...,...,...,...,...
252,CO0010500,"ADAMS, JEFFERSON",True,39.863120,-105.050415,CO,Colorado,Westminster Police Department,City,1997-01-01,"ADAMS, JEFFERSON"
253,CO0030600,"ARAPAHOE, JEFFERSON",True,39.619427,-105.046050,CO,Colorado,Bow Mar Police Department,City,1997-01-01,"ARAPAHOE, JEFFERSON"
254,CO0550100,"RIO GRANDE, SAGUACHE",True,38.031651,-106.234666,CO,Colorado,Center Police Department,City,1997-01-01,"RIO GRANDE, SAGUACHE"
255,CO0010100,"ADAMS, ARAPAHOE, DOUGLAS",True,39.709550,-104.814930,CO,Colorado,Aurora Police Department,City,1985-01-01,"ADAMS, ARAPAHOE, DOUGLAS"
256,CO0030200,"ARAPAHOE, DOUGLAS, JEFFERSON",True,39.616898,-105.014540,CO,Colorado,Littleton Police Department,City,2011-01-01,"ARAPAHOE, DOUGLAS, JEFFERSON"

In [5]:
ori_CO_list = df_CO['ori'].unique().tolist()
len(ori_CO_list)

257

In [6]:
with open('../DATA/RAW_CRIME_DATA/response_1771261621909.json') as f:
    data = json.load(f)

all_agencies = []

for county, agencies in data.items():
    for agency in agencies:
        agency['county_name'] = county
        all_agencies.append(agency)

df_NM = pd.DataFrame(all_agencies)

df_NM

,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,agency_type_name,nibrs_start_date,county_name
0,NM0130500,LEA,False,32.795687,-103.413271,NM,New Mexico,Tatum Police Department,City,None,LEA
1,NM0130000,LEA,True,32.935955,-103.341995,NM,New Mexico,Lea County Sheriff's Office,County,2020-10-01,LEA
2,NM0130100,LEA,True,32.795687,-103.413271,NM,New Mexico,Eunice Police Department,City,2021-01-01,LEA
3,NM0130200,LEA,True,32.702976,-103.136190,NM,New Mexico,Hobbs Police Department,City,2020-01-01,LEA
4,NM0130300,LEA,True,32.795687,-103.413271,NM,New Mexico,Jal Police Department,City,2021-01-01,LEA
...,...,...,...,...,...,...,...,...,...,...,...
130,NMDI08300,NOT SPECIFIED,True,NaN,NaN,NM,New Mexico,Zia Pueblo,Tribal,2021-01-01,NOT SPECIFIED
131,NMNSP0000,UNMAPPED COUNTY,True,35.513731,-105.966439,NM,New Mexico,New Mexico State Police,State Police,2023-04-01,UNMAPPED COUNTY
132,NM0230600,"BERNALILLO, SANDOVAL",True,35.268604,-106.634796,NM,New Mexico,Rio Rancho Police Department,City,2020-12-01,"BERNALILLO, SANDOVAL"
133,NM0261200,"BERNALILLO, SANTA FE",True,35.513731,-105.966439,NM,New Mexico,Edgewood Police Department,City,2021-02-01,"BERNALILLO, SANTA FE"
134,NM0210100,"RIO ARRIBA, SANTA FE",False,36.509669,-106.693983,NM,New Mexico,Espanola Police Department,City,None,"RIO ARRIBA, SANTA FE"

In [7]:
ori_NM_list = df_NM['ori'].unique().tolist()
len(ori_NM_list)

135

In [8]:
with open('../DATA/RAW_CRIME_DATA/CO0050100.json') as f:
    data = json.load(f)


agency_name = "Springfield Police Department Arrests"

rates = data['rates'][agency_name]
actuals = data['actuals'][agency_name]
population = data['populations']['population']["Springfield Police Department"]
participated_pop = data['populations']['participated_population']["Springfield Police Department"]

df = pd.DataFrame({
    'month': rates.keys(),
    'rate_per_100k': rates.values(),
    'actual_arrests': actuals.values(),
    'population': population.values(),
    'participated_population': participated_pop.values()
})

df['month'] = pd.to_datetime(df['month'], format='%m-%Y')

df.sort_values('month', inplace=True)
df.reset_index(drop=True, inplace=True)

df

,month,rate_per_100k,actual_arrests,population,participated_population
0,2024-01-01,78.13,1,1280,1280
1,2024-02-01,546.88,7,1280,1280
2,2024-03-01,312.50,4,1280,1280
3,2024-04-01,234.38,3,1280,1280
4,2024-05-01,234.38,3,1280,1280
5,2024-06-01,546.88,7,1280,1280
6,2024-07-01,390.63,5,1280,1280
7,2024-08-01,468.75,6,1280,1280
8,2024-09-01,156.25,2,1280,1280
9,2024-10-01,156.25,2,1280,1280
10,2024-11-01,234.38,3,1280,1280
11,2024-12-01,234.38,3,1280,1280

In [9]:
max_lat_NM = df_NM['latitude'].max()
min_lat_NM = df_NM['latitude'].min()

max_lon_NM = df_NM['longitude'].max()
min_lon_NM = df_NM['longitude'].min()

print(f"The maximum latitude is: {max_lat_NM}")
print(f"The minimum latitude is: {min_lat_NM}")

print(f"\nThe maximum longitude is: {max_lon_NM}")
print(f"The minimum longitude is: {min_lon_NM}")

The maximum latitude is: 36.90456
The minimum latitude is: 31.795942

The maximum longitude is: -103.13619
The minimum longitude is: -108.745729

In [10]:
max_lat_CO = df_CO['latitude'].max()
min_lat_CO = df_CO['latitude'].min()

max_lon_CO = df_CO['longitude'].max()
min_lon_CO = df_CO['longitude'].min()

print(f"The maximum latitude is: {max_lat_CO}")
print(f"The minimum latitude is: {min_lat_CO}")

print(f"\nThe maximum longitude is: {max_lon_CO}")
print(f"The minimum longitude is: {min_lon_CO}")

The maximum latitude is: 40.988636
The minimum latitude is: 37.202395

The maximum longitude is: -102.22071
The minimum longitude is: -108.80293

In [11]:
import matplotlib.pyplot as plt

df_plot_NM = df_NM.dropna(subset=['latitude', 'longitude'])
df_plot_CO = df_CO.dropna(subset=['latitude', 'longitude'])

#plt.figure(figsize=(8,6))
#plt.scatter(df_plot_NM['longitude'], df_plot_NM['latitude'])
#for i, row in df_plot_NM.iterrows():
    #plt.text(row['longitude'], row['latitude'], row['agency_name'], fontsize=6)
#plt.xlabel("Longitude")
#plt.ylabel("Latitude")
#plt.title("New Mexico Law Enforcement Agencies")

#plt.show()

In [16]:
# Run if folium not installed
# !pip install folium

In [14]:
import folium

map_NM = folium.Map(location=[34.5, -105.5], zoom_start=7)

for _, row in df_plot_NM.iterrows():
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=row['agency_name']
    ).add_to(map_NM)

map_NM

In [17]:
map_CO = folium.Map(location=[39.0, -105.5], zoom_start=7)

for _, row in df_plot_CO.iterrows():
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=row['agency_name']
    ).add_to(map_CO)

map_CO

In [19]:
def build_agency_df(data, ori):

    if 'actuals' not in data or len(data['actuals']) == 0:
        return None

    agency_label = next(iter(data['actuals']))

    rates = data['rates'].get(agency_label, {})
    actuals = data['actuals'].get(agency_label, {})

    agency_name = agency_label.replace(" Arrests","")

    population = data['populations']['population'].get(agency_name, {})
    participated_pop = data['populations']['participated_population'].get(agency_name, {})

    df = pd.DataFrame({
        'month': rates.keys(),
        'actual_arrests': actuals.values(),
        'rate_per_100k': rates.values(),
        'population': population.values(),
        'participated_population': participated_pop.values()
    })

    df['month'] = pd.to_datetime(df['month'], format='%m-%Y')
    df['ori'] = ori

    return df.sort_values('month').reset_index(drop=True)

In [18]:
import requests

API_KEY = "HdJoOraec3MgSMMu6Q1Y5dIC8UkTcpiqKSNIQTDn"

def get_agency_arrests(ori):
    
    url = f"https://api.usa.gov/crime/fbi/cde/arrest/agency/{ori}/all"
    params = {
        "type": "counts",
        "from": "01-2024",
        "to": "12-2024",
        "api_key": "HdJoOraec3MgSMMu6Q1Y5dIC8UkTcpiqKSNIQTDn"
    }
    
    r = requests.get(url, params=params)

    if r.status_code != 200:
        print(f"Failed for {ori}")
        return None

    data = r.json()

    return build_agency_df(data, ori)

CAUTION: This next piece of code only runs properly when the FBI API is accepting requests. The API server occasionally does not run.

In [21]:
all_CO_dfs = []

for ori in ori_CO_list:
    df_temp = get_agency_arrests(ori)
    if df_temp is not None:
        all_CO_dfs.append(df_temp)

master_CO_df = pd.concat(all_CO_dfs, ignore_index=True)

C:\Users\laura\AppData\Local\Temp\ipykernel_27788\3736921688.py:8: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  master_CO_df = pd.concat(all_CO_dfs, ignore_index=True)

In [22]:
master_CO_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3084 entries, 0 to 3083
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   month                    3084 non-null   datetime64[ns]
 1   actual_arrests           2651 non-null   float64
 2   rate_per_100k            2651 non-null   float64
 3   population               2940 non-null   object
 4   participated_population  2651 non-null   float64
 5   ori                      3084 non-null   object
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 144.7+ KB

In [23]:
master_CO_df

,month,actual_arrests,rate_per_100k,population,participated_population,ori
0,2024-01-01,NaN,NaN,504,NaN,CO0050700
1,2024-02-01,NaN,NaN,504,NaN,CO0050700
2,2024-03-01,NaN,NaN,504,NaN,CO0050700
3,2024-04-01,NaN,NaN,504,NaN,CO0050700
4,2024-05-01,NaN,NaN,504,NaN,CO0050700
...,...,...,...,...,...,...
3079,2024-08-01,55.0,124.78,44076,44076.0,CO0030200
3080,2024-09-01,49.0,111.17,44076,44076.0,CO0030200
3081,2024-10-01,59.0,133.86,44076,44076.0,CO0030200
3082,2024-11-01,46.0,104.37,44076,44076.0,CO0030200
3083,2024-12-01,80.0,181.50,44076,44076.0,CO0030200

In [25]:
master_CO_df.to_csv('../DATA/PROCESSED_CRIME_DATA/CO_monthly_county_arrests.csv')

CAUTION: This next piece of code only runs properly when the FBI API is accepting requests. The API server occasionally does not run.<br>
Failure message: upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure

In [26]:
all_NM_dfs = []

for ori in ori_NM_list:
    df_temp = get_agency_arrests(ori)
    if df_temp is not None:
        all_NM_dfs.append(df_temp)

master_NM_df = pd.concat(all_NM_dfs, ignore_index=True)

Failed for NM0130500
Failed for NM0130000
Failed for NM0130100
Failed for NM0130200
Failed for NM0130300
Failed for NM0130400
Failed for NM0080300
Failed for NM0080200
Failed for NM0080100
Failed for NM0080000
Failed for NM0080500
Failed for NM0160000
Failed for NM0160100
Failed for NM0180000

KeyboardInterrupt:

In [ ]:
master_NM_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1620 entries, 0 to 1619
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   month                    1620 non-null   datetime64[ns]
 1   actual_arrests           1620 non-null   float64
 2   rate_per_100k            1620 non-null   float64
 3   population               1620 non-null   int64
 4   participated_population  1620 non-null   float64
 5   ori                      1620 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 76.1+ KB

In [ ]:
master_NM_df = master_NM_df.fillna(0)

In [ ]:
master_NM_df.to_csv('../DATA/PROCESSED_CRIME_DATA/NM_monthly_county_arrests.csv')

In [ ]:
summed_NM_df = (
    master_NM_df.groupby('ori', as_index=False)
      .agg(
          Arrests_2024=('actual_arrests', 'sum'),
          Population_2024=('population', 'first')
      )
)

summed_NM_df

           ori  Arrests_2024  Population_2024
0    NM0010000        3204.0           116455
1    NM0010100       16166.0           558745
2    NM0010200         143.0                0
3    NM0011200           0.0                0
4    NM0020000           2.0             3932
..         ...           ...              ...
130  NMDI05500           0.0                0
131  NMDI05700         309.0                0
132  NMDI07000         294.0                0
133  NMDI08300          44.0                0
134  NMNSP0000           4.0                0

[135 rows x 3 columns]

In [ ]:
merged_NM_df = pd.merge(df_NM, summed_NM_df, on='ori')

In [ ]:
merged_NM_df.to_csv('../DATA/PROCESSED_CRIME_DATA/NM_arrests_2024.csv')

In [ ]:
master_CO_df = master_CO_df.fillna(0)

C:\Users\emily\AppData\Local\Temp\ipykernel_21728\701378400.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  master_CO_df = master_CO_df.fillna(0)

In [ ]:
summed_CO_df = (
    master_CO_df.groupby('ori', as_index=False)
      .agg(
          Arrests_2024=('actual_arrests', 'sum'),
          Population_2024=('population', 'first')
      )
)

summed_CO_df

           ori  Arrests_2024  Population_2024
0    CO0010000        6237.0           103829
1    CO0010100       10432.0           397852
2    CO0010200        1967.0            43231
3    CO0010300        1994.0            70170
4    CO0010400        5184.0           145847
..         ...           ...              ...
252  COCBI0000          69.0                0
253  COCSP0000        5247.0                0
254  CODI01100         389.0                0
255  CODMV0000           0.0                0
256  CODPD0000       24363.0           722031

[257 rows x 3 columns]

In [ ]:
merged_CO_df = pd.merge(df_CO, summed_CO_df, on='ori')

merged_CO_df

,ori,counties,is_nibrs,latitude,longitude,state_abbr,state_name,agency_name,agency_type_name,nibrs_start_date,county_name,Arrests_2024,Population_2024
0,CO0050700,BACA,True,37.306678,-102.537765,CO,Colorado,Walsh Police Department,City,2004-10-01,BACA,0.0,504
1,CO0050000,BACA,True,37.412470,-102.614260,CO,Colorado,Baca County Sheriff's Office,County,1997-01-01,BACA,0.0,1543
2,CO0050100,BACA,True,37.406647,-102.616520,CO,Colorado,Springfield Police Department,City,2003-01-01,BACA,46.0,1280
3,CO0060000,BENT,True,37.931891,-103.077584,CO,Colorado,Bent County Sheriff's Office,County,1997-01-01,BENT,129.0,5800
4,CO0330000,LAKE,True,39.205341,-106.350079,CO,Colorado,Lake County Sheriff's Office,County,1997-01-01,LAKE,125.0,4780
...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,CO0010500,"ADAMS, JEFFERSON",True,39.863120,-105.050415,CO,Colorado,Westminster Police Department,City,1997-01-01,"ADAMS, JEFFERSON",3467.0,114310
253,CO0030600,"ARAPAHOE, JEFFERSON",True,39.619427,-105.046050,CO,Colorado,Bow Mar Police Department,City,1997-01-01,"ARAPAHOE, JEFFERSON",0.0,814
254,CO0550100,"RIO GRANDE, SAGUACHE",True,38.031651,-106.234666,CO,Colorado,Center Police Department,City,1997-01-01,"RIO GRANDE, SAGUACHE",60.0,1922
255,CO0010100,"ADAMS, ARAPAHOE, DOUGLAS",True,39.709550,-104.814930,CO,Colorado,Aurora Police Department,City,1985-01-01,"ADAMS, ARAPAHOE, DOUGLAS",10432.0,397852
256,CO0030200,"ARAPAHOE, DOUGLAS, JEFFERSON",True,39.616898,-105.014540,CO,Colorado,Littleton Police Department,City,2011-01-01,"ARAPAHOE, DOUGLAS, JEFFERSON",631.0,44076

In [ ]:
merged_CO_df.to_csv('../DATA/PROCESSED_CRIME_DATA/CO_arrests_2024.csv')

https://www.census.gov/quickfacts/fact/table/CO/PST045224<br>
Colorado<br>
Population estimates, July 1, 2024, (V2024)<br>
5,957,493

In [ ]:
merged_CO_df['Population_2024'].sum()

np.int64(5957493)

https://www.census.gov/quickfacts/fact/table/NM/PST045224<br>
New Mexico<br>
Population estimates, July 1, 2024, (V2024) <br>
2,130,256

In [ ]:
merged_NM_df['Population_2024'].sum()

np.int64(2130256)